### ISSUE TITLE
EOFWhileReadingLineException

### ISSUE THREAD

**Issue by niklasbulitta** [membrane/service-proxy#108]
We receive random EOFWhileReadingLineExceptions while proxying a webpage. We do this for rapid prototyping (enhance the html with custom css, js, content). We're using membrane 4.0.2

This is the full exception:

An exception occured while handling a request: 
com.predic8.membrane.core.transport.http.EOFWhileReadingLineException
    at com.predic8.membrane.core.util.HttpUtil.readLine(HttpUtil.java:63)
    at com.predic8.membrane.core.http.Response.parseStartLine(Response.java:253)
    at com.predic8.membrane.core.http.Response.read(Response.java:267)
    at com.predic8.membrane.core.transport.http.HttpClient.doCall(HttpClient.java:211)
    at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:146)
    at com.predic8.membrane.core.interceptor.HTTPClientInterceptor.handleRequest(HTTPClientInterceptor.java:55)
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
    at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:69)
    at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:182)
    at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:87)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)

Any ideas?

**Comment by matseku** [comment]
Hi,

I was experiencing exactly the behavior described in the first and the preceding posts in this thread. 

I discovered that the HTTP responses from the remote server contained no KEEP-ALIVE header (and I presume the server closes the connection immediately after sending a HTTP response).

By lowering the keep-alive setting of Membrane's HTTP client interceptor to the minimum value (1ms I guess), the problem with NoResponse exceptions seems to be gone.

Thanks,
Mats

**Comment by rrayst** [comment]
Hi Matseku,

in HTTP/1.1, connections are keep-alive by default: https://en.wikipedia.org/wiki/HTTP_persistent_connection#HTTP_1.1

Best, Tobias

**Comment by matseku** [comment]
Hi again Tobias,

While troubleshooting some semi-random errors in my Membrane app I again stumbled upon the same exception reported by niklasbulitta in this thread. And again I was able to get rid of the errors by reducing the keepalivetimeout on the httpClientConfig/connection element, to 1ms. 

And I was wondering why Membrane doesn't handle this situation (by making a new request on a new connection) instead of giving up and returning an empty HTTP 200 OK response to the client?

Thanks!

Bests, Mats

**Comment by rrayst** [comment]
Opening a new TCP connection for every request introduces a significant delay (2*network latency).
