### ISSUE TITLE
serviceProxy attribute IP : conceptual bug 

### ISSUE THREAD

**Issue by vlk32** [membrane/service-proxy#170]
I've spent 2 days with strange behaviour. 

```
org.springframework.context.ApplicationContextException: Failed to start bean 'router'; nested exception is java.lang.RuntimeException: com.predic8.membrane.core.transport.PortOccupiedException: Opening a serversocket at port 80 failed. Please make sure that the port is not occupied by a different program or change your rule configuration to select another one.
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:170) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:339) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:143) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:89) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1278) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at com.predic8.membrane.core.HotDeploymentThread.reload(HotDeploymentThread.java:109) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at com.predic8.membrane.core.HotDeploymentThread.run(HotDeploymentThread.java:83) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
Caused by: java.lang.RuntimeException: com.predic8.membrane.core.transport.PortOccupiedException: Opening a serversocket at port 80 failed. Please make sure that the port is not occupied by a different program or change your rule configuration to select another one.
        at com.predic8.membrane.core.Router.start(Router.java:270) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:167) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        ... 7 common frames omitted
Caused by: com.predic8.membrane.core.transport.PortOccupiedException: Opening a serversocket at port 80 failed. Please make sure that the port is not occupied by a different program or change your rule configuration to select another one.
        at com.predic8.membrane.core.transport.http.HttpEndpointListener.<init>(HttpEndpointListener.java:57) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at com.predic8.membrane.core.transport.http.HttpTransport.openPort(HttpTransport.java:162) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at com.predic8.membrane.core.RuleManager.openPorts(RuleManager.java:162) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        at com.predic8.membrane.core.Router.start(Router.java:257) ~[mdf-rbp-sso-2.0.0.0-SNAPSHOT.jar:na]
        ... 8 common frames omitted
```

Configuration contains something like this :

``` xml
  <serviceProxy name="A" port="80">...</serviceProxy>
  <serviceProxy name="B" port="80" ip="localhost">...</serviceProxy>
  <serviceProxy name="C" port="80" ip="127.0.0.1">...</serviceProxy>
```

I investigate the code and realised that each proxy tryed to start new `HttpEndpointListener thread`, 
- `A` is going to listen on `*:80` this means port `80` on all IP-adresses including `127.0.0.1`
- `B` is going to listen on `localhost:80` this means port `80` on localhost which is `127.0.0.1`
- `C` is going to listen on `127.0.0.1:80` this means port `80` on `127.0.0.1`

So all of that threads wants to listen on the same address and port. This is not allowed.
There was attempt in the code to solve this situation ( look at `HttpTransport.portListenerMapping` ), but this could work for `B`. and `C`, because there is in different way written localhost interface. This could be easily solved by transforming DNS-name to IP-address, before inserting to the `HttpTransport.portListenerMapping`

The combination `A` and `B`/`C` is much worse. Service `A` wants to listen on all interfaces but `B`/`C` only on localhost. There has to be conceptual change in starting `HttpEndpointListener threads`
1. start all services without `ip-attribute` on port `XY`
2. for each service with `ip-attribute with value ABCD`
- transform name to IP : `ip = InetAddress.getByName(ABCD)`
- check if there was started thread listened on `*:XY`
  - if `yes`, then don't start new thread, but add IP-filter to the service definition
  - if `no` and there wasn't already started thread listened on `ip:XY`, then start `new HttpEndpointListener`

**Comment by rrayst** [comment]
Thanks for the pull request. It has effectively been mergen into master. I'm closing the issue because opening multiple serviceProxies with the same "port", but different (although effectively equal) "host", attributes is quite rare.
