### ISSUE TITLE
soap ssl tunel

### ISSUE THREAD

**Issue by ali-rezvani** [membrane/service-proxy#178]
Hi.
It is my first try with membrane service proxy and i want configure a SSL Tunnel to the Server in soap service.
This is my proxy configuratin:
       
      
       <soapProxy port="9090" wsdl="https://estelam.nibn.net:443/IBANSpecEnquiry/IBANSpec?wsdl">	
            <ssl ignoreTimestampCheckFailure="true">
				<keystore    location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks"    password="password" />
                <truststore  location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks" password="password" />
            </ssl>
			
		</soapProxy>

But when i starting service this error was occured:

      org.springframework.context.ApplicationContextException: Failed to start bean 'r
      outer'; nested exception is java.lang.RuntimeException: java.lang.IllegalArgumen
      tException: Could not download the WSDL 'https://estelam.nibn.net:443/IBANSpecEn
      quiry/IBANSpec?wsdl'.
              at org.springframework.context.support.DefaultLifecycleProcessor.doStart
      (DefaultLifecycleProcessor.java:170)
              at org.springframework.context.support.DefaultLifecycleProcessor.access$
      1(DefaultLifecycleProcessor.java:154)
              at org.springframework.context.support.DefaultLifecycleProcessor$Lifecyc
      leGroup.start(DefaultLifecycleProcessor.java:339)
              at org.springframework.context.support.DefaultLifecycleProcessor.startBe
      ans(DefaultLifecycleProcessor.java:143)
              at org.springframework.context.support.DefaultLifecycleProcessor.start(D
      efaultLifecycleProcessor.java:89)
              at org.springframework.context.support.AbstractApplicationContext.start(
      AbstractApplicationContext.java:1259)
              at com.predic8.membrane.core.Router.init(Router.java:138)
              at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:38)
              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
              at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
              at java.lang.reflect.Method.invoke(Unknown Source)
              at com.predic8.membrane.core.Starter.main(Starter.java:26)
      Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Could
       not download the WSDL 'https://estelam.nibn.net:443/IBANSpecEnquiry/IBANSpec?ws
      dl'.
              at com.predic8.membrane.core.Router.start(Router.java:270)
              at org.springframework.context.support.DefaultLifecycleProcessor.doStart
      (DefaultLifecycleProcessor.java:167)
              ... 12 more
      Caused by: java.lang.IllegalArgumentException: Could not download the WSDL 'http
      s://estelam.nibn.net:443/IBANSpecEnquiry/IBANSpec?wsdl'.
              at com.predic8.membrane.core.rules.SOAPProxy.parseWSDL(SOAPProxy.java:15
      1)
              at com.predic8.membrane.core.rules.SOAPProxy.configure(SOAPProxy.java:19
      4)
              at com.predic8.membrane.core.rules.SOAPProxy.init(SOAPProxy.java:268)
              at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java
      :180)
              at com.predic8.membrane.core.Router.init(Router.java:241)
              at com.predic8.membrane.core.Router.start(Router.java:256)
              ... 13 more
      Caused by: java.lang.RuntimeException: com.predic8.membrane.core.resolver.Resour
      ceRetrievalException: com.predic8.membrane.core.transport.http.EOFWhileReadingFi
      rstLineException: null line so far: "§♥☺ ☻☻
      " while retrieving https://estelam.nibn.net:443/IBANSpecEnquiry/IBANSpec?wsdl
              at com.predic8.membrane.core.resolver.ResolverMap$ExternalResolverConver
      ter$1.resolveViaHttp(ResolverMap.java:238)
              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
              at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
              at java.lang.reflect.Method.invoke(Unknown Source)
              at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMet
      hodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
              at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(P
      ogoMetaMethodSite.java:52)
              at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent
      (CallSiteArray.java:49)
              at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
      tractCallSite.java:133)
              at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
      tractCallSite.java:141)
              at com.predic8.xml.util.ExternalResolver.resolve(ExternalResolver.groovy
      :66)
              at com.predic8.xml.util.ExternalResolver$resolve.call(Unknown Source)
              at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSi
      teArray.java:45)
              at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
      llSite.java:108)
              at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
      llSite.java:120)
              at com.predic8.soamodel.AbstractParser.getResourceToken(AbstractParser.g
      roovy:45)
              at com.predic8.soamodel.AbstractParser.this$2$getResourceToken(AbstractP
      arser.groovy)
              at com.predic8.soamodel.AbstractParser$this$2$getResourceToken.callCurre                          
         nt(Unknown Source)
              at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent
         (CallSiteArray.java:49)
                 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
         tractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
         tractCallSite.java:141)
        at com.predic8.soamodel.AbstractParser.parse(AbstractParser.groovy:34)
        at com.predic8.wsdl.WSDLParser.super$2$parse(WSDLParser.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
         90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1074)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper
         N(ScriptBytecodeAdapter.java:128)
        at com.predic8.wsdl.WSDLParser.parse(WSDLParser.groovy:29)
        at com.predic8.membrane.core.rules.SOAPProxy.parseWSDL(SOAPProxy.java:96
         )
        ... 18 more
         Caused by: com.predic8.membrane.core.resolver.ResourceRetrievalException: com.pr
         edic8.membrane.core.transport.http.EOFWhileReadingFirstLineException: null line
         so far: "§♥☺ ☻☻
         " while retrieving https://estelam.nibn.net:443/IBANSpecEnquiry/IBANSpec?wsdl
        at com.predic8.membrane.core.resolver.HTTPSchemaResolver.resolve(HTTPSch
         emaResolver.java:67)
        at com.predic8.membrane.core.resolver.ResolverMap$ExternalResolverConver
         ter$1.resolveViaHttp(ResolverMap.java:236)
        ... 50 more
         Caused by: com.predic8.membrane.core.transport.http.EOFWhileReadingFirstLineExce
         ption: null line so far: "§♥☺ ☻☻
         "
        at com.predic8.membrane.core.http.Response.parseStartLine(Response.java:
         295)
        at com.predic8.membrane.core.http.Response.read(Response.java:312)
        at com.predic8.membrane.core.transport.http.HttpClient.doCall(HttpClient
         .java:252)
        at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.j
         ava:157)
        at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.j
         ava:124)
        at com.predic8.membrane.core.resolver.HTTPSchemaResolver.resolve(HTTPSch
         emaResolver.java:56)
        ... 51 more
		 
Thank you

**Comment by predic8** [comment]
You can download the WSDL and save a lokal copy that you reference in the soapProxy or you can create an serviceProxy for the WSDL:

```
<serviceProxy port="2010">
  <ssl ignoreTimestampCheckFailure="true">
    <keystore    location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks"    password="password" />
    <truststore  location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks" password="password" />    
  </ssl>
  <target host="estelam.nibn.net" port="443"/>
</serviceProxy>

```

Try if you can get the WSDL without SSL from http://localhost:2010/IBANSpecEnquiry/IBANSpec?wsdl
Than you can use that WSDL in your soapProxy:

```
   <soapProxy port="9090" wsdl="http://localhost:2010/IBANSpecEnquiry/IBANSpec?wsdl">    
        <ssl ignoreTimestampCheckFailure="true">
            <keystore    location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks"    password="password" />
            <truststore  location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks" password="password" />
        </ssl>

    </soapProxy>
```

**Comment by ali-rezvani** [comment]
Thank you predic8 for your attention.
I have noticed to your recommend and add serviceProxy tag.
When i embed ssl tag in serviceProxy tag like that you recommend this error was occured:

      org.springframework.context.ApplicationContextException: Failed to start bean 
     'router'; nested exception is java.lang.RuntimeException: java.lang.RuntimeException:
      Could not extract DNS names from the first key's certificate in
      C:/java/membrane-service-proxy-4.0.18/conf/iban.jks


But when i embed ssl tag inside target tag like this:

       	<serviceProxy port="80">		 
            <target host="estelam.nibn.net" port="443">	
			    <ssl ignoreTimestampCheckFailure="true" protocol="TLS">
                    <keystore    location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks"    password="password" />
                    <truststore  location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks" password="password" />    
                </ssl>				
            </target>
        </serviceProxy>

I can can get the WSDL without SSL from http://localhost/IBANSpecEnquiry/IBANSpec?wsdl
in browser.
But when i add wsdl to soapProxy tag this error occure:

             00:48:16,280  INFO DefaultLifecycleProcessor:334 - Starting beans in phase 0
       00:48:16,282  INFO Router:247 - Starting Membrane Service Proxy 4.0.18
       00:48:17,924  INFO HttpClient:171 - Connection to localhost:80 refused.
       00:48:19,174  INFO HttpClient:171 - Connection to localhost:80 refused.
       00:48:20,424  INFO HttpClient:171 - Connection to localhost:80 refused.
       00:48:21,684  INFO HttpClient:171 - Connection to localhost:80 refused.
       00:48:22,944  INFO HttpClient:171 - Connection to localhost:80 refused.
       org.springframework.context.ApplicationContextException: Failed to start bean 'r
       outer'; nested exception is java.lang.RuntimeException: java.net.ConnectExceptio
       n: Connection refused: connect
               at org.springframework.context.support.DefaultLifecycleProcessor.doStart
       (DefaultLifecycleProcessor.java:170)
               at org.springframework.context.support.DefaultLifecycleProcessor.access$
       1(DefaultLifecycleProcessor.java:154)
               at org.springframework.context.support.DefaultLifecycleProcessor$Lifecyc
       leGroup.start(DefaultLifecycleProcessor.java:339)
               at org.springframework.context.support.DefaultLifecycleProcessor.startBe
       ans(DefaultLifecycleProcessor.java:143)
               at org.springframework.context.support.DefaultLifecycleProcessor.start(D
       efaultLifecycleProcessor.java:89)
               at org.springframework.context.support.AbstractApplicationContext.start(
       AbstractApplicationContext.java:1259)
               at com.predic8.membrane.core.Router.init(Router.java:138)
               at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:38)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
               at java.lang.reflect.Method.invoke(Unknown Source)
               at com.predic8.membrane.core.Starter.main(Starter.java:26)
       Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection ref
       used: connect
               at com.predic8.membrane.core.Router.start(Router.java:270)
               at org.springframework.context.support.DefaultLifecycleProcessor.doStart
       (DefaultLifecycleProcessor.java:167)
               ... 12 more
       Caused by: java.net.ConnectException: Connection refused: connect
               at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
               at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
               at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
               at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
               at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
               at java.net.PlainSocketImpl.connect(Unknown Source)
               at java.net.SocksSocketImpl.connect(Unknown Source)
               at java.net.Socket.connect(Unknown Source)
               at com.predic8.membrane.core.transport.http.Connection.open(Connection.j
       ava:90)
               at com.predic8.membrane.core.transport.http.ConnectionManager.getConnect
       ion(ConnectionManager.java:152)
               at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.j
       ava:153)
               at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.j
       ava:124)
               at com.predic8.membrane.core.resolver.HTTPSchemaResolver.resolve(HTTPSch
       emaResolver.java:56)
               at com.predic8.membrane.core.resolver.ResolverMap$ExternalResolverConver
       ter$1.resolveViaHttp(ResolverMap.java:236)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
               at java.lang.reflect.Method.invoke(Unknown Source)
               at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMet
       hodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
               at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(P
       ogoMetaMethodSite.java:52)
               at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent
       (CallSiteArray.java:49)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
       tractCallSite.java:133)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
       tractCallSite.java:141)
               at com.predic8.xml.util.ExternalResolver.resolve(ExternalResolver.groovy
       :66)
               at com.predic8.xml.util.ExternalResolver$resolve.call(Unknown Source)
               at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSi
       teArray.java:45)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
       llSite.java:108)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
       llSite.java:120)
               at com.predic8.soamodel.AbstractParser.getResourceToken(AbstractParser.g
       roovy:45)
               at com.predic8.soamodel.AbstractParser.this$2$getResourceToken(AbstractP
       arser.groovy)
               at com.predic8.soamodel.AbstractParser$this$2$getResourceToken.callCurre
       nt(Unknown Source)
               at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent
       (CallSiteArray.java:49)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
       tractCallSite.java:133)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
       tractCallSite.java:141)
               at com.predic8.soamodel.AbstractParser.parse(AbstractParser.groovy:34)
               at com.predic8.wsdl.WSDLParser.super$2$parse(WSDLParser.groovy)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
               at java.lang.reflect.Method.invoke(Unknown Source)
               at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
       90)
               at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
               at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1074)
               at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper
       N(ScriptBytecodeAdapter.java:128)
               at com.predic8.wsdl.WSDLParser.parse(WSDLParser.groovy:29)
               at com.predic8.membrane.core.rules.SOAPProxy.parseWSDL(SOAPProxy.java:96
       )
               at com.predic8.membrane.core.rules.SOAPProxy.configure(SOAPProxy.java:19
       4)
               at com.predic8.membrane.core.rules.SOAPProxy.init(SOAPProxy.java:268)
               at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java
       :180)
               at com.predic8.membrane.core.Router.init(Router.java:241)
               at com.predic8.membrane.core.Router.start(Router.java:256)
               ... 13 more

**Comment by keshavarzi** [comment]
Hi,

Am 27.01.15 um 10:03 schrieb ali-rezvani:
>
> Thank you predic8 for your attention.
> I have noticed to your recommend and add serviceProxy tag.
> When i embed ssl tag in serviceProxy tag like that you recommend this 
> error was occured:
>
> |   org.springframework.context.ApplicationContextException: Failed to start bean
>   'router'; nested exception is java.lang.RuntimeException: java.lang.RuntimeException:
>    Could not extract DNS names from the first key's certificate in
>    C:/java/membrane-service-proxy-4.0.18/conf/iban.jks
> |
>
> But when i embed ssl tag inside target tag like this:
>
> |     <serviceProxy port="80">
>          <target host="estelam.nibn.net" port="443">
>              <ssl ignoreTimestampCheckFailure="true" protocol="TLS">
>                  <keystore    location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks"    password="password" />
>                  <truststore  location="C:/java/membrane-service-proxy-4.0.18/conf/iban.jks" password="password" />
>              </ssl>
>          </target>
>      </serviceProxy>|
|You are right. The ssl should go into the target cause the connection 
to the target is secured.|
> |
> |
>
> I can can get the WSDL without SSL from 
> http://localhost/IBANSpecEnquiry/IBANSpec?wsdl
> in browser.
> But when i add wsdl to soapProxy tag this error occure:
>
The problem is that the soapProxy tries to retrieve the WSDL before the 
serviceProxy for the WSDL is started. I think we have a solution for 
that. I will ask a coworker and come back to you. To get going until 
then you can download the WSDL and reference it from there.

Cheers,
Thomas

**Comment by ali-rezvani** [comment]
Thank you Thomas.
I download wsdl and save it in local.I can to get wsdl in browser.
I test service with soapUI and can get methods of service.But when i call methods with arguments
request time oute exception occured.

**Comment by predic8** [comment]
Hi,

Am 27.01.15 um 11:11 schrieb ali-rezvani:
>
> Thank you Thomas.
> I download wsdl and save it in local.I can to get wsdl in browser.
> I test service with soapUI and can get methods of service.But when i 
> call methods with arguments
> request time oute exception occured.
>
Where did the exception occour and what exception? Can you provide a 
sample of the request and the stacktrace?

Cheers,
Thomas

> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/membrane/service-proxy/issues/178#issuecomment-71620971>.
>

Viele Grüße,
Thomas Bayer

-- 
predic8 GmbH
Moltkestr. 40

53173 Bonn

http://predic8.de
Tel: +49 (0) 228 5552576-0
Fax: +49 (0) 228 5552576-50

Amtsgericht Bonn
HRB 16152
Geschäftsführer: Thomas Bayer

**Comment by ali-rezvani** [comment]
I see this error in soapUI :
 Error getting response: org.apache.http.NoHttpResponseException: The target server failed to respond

**Comment by keshavarzi** [comment]
Am 27.01.15 um 11:35 schrieb ali-rezvani:
>
> I see this error in soapUI :
> Error getting response: org.apache.http.NoHttpResponseException: The 
> target server failed to respond
>
And what was the server? Was Membrane in between?

**Comment by ali-rezvani** [comment]
Server is a banking service in vpn called IBAN.
And i want to use membrane between as proxy to consume soap services without meeting ssl complexity

**Comment by predic8** [comment]
Hi,

we should continue this at:

https://groups.google.com/forum/?hl=en&fromgroups=#!forum/membrane-monitor

not in this issue here.

Am 27.01.15 um 11:50 schrieb ali-rezvani:
>
> Server is a banking service in vpn called IBAN.
> And i want to use membrane between as proxy to consume soap services 
> without meeting ssl complexity
>
Do you get the error with or without Membrane in between? If you get it 
with Membrane than have a look at the Membrane log or console.

Cheers,
Thomas




> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/membrane/service-proxy/issues/178#issuecomment-71625944>.
>

Viele Grüße,
Thomas Bayer

-- 
predic8 GmbH
Moltkestr. 40

53173 Bonn

http://predic8.de
Tel: +49 (0) 228 5552576-0
Fax: +49 (0) 228 5552576-50

Amtsgericht Bonn
HRB 16152
Geschäftsführer: Thomas Bayer

**Comment by symle** [comment]
If it possible could you give me only the wsdl

**Comment by predic8** [comment]
?
