### ISSUE TITLE
Using <import> without a schemaLocation in a wsdl file causes a NullPointerException on startup

### ISSUE THREAD

**Issue by longsonr** [membrane/service-proxy#179]
proxies.xml

    <spring:beans xmlns="http://membrane-soa.org/proxies/1/"
	    xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
					    http://membrane-soa.org/proxies/1/ http://membrane-soa.org/schemas/proxies-1.xsd">
	    <router>
		    <soapProxy port="20002" wsdl="test.wsdl">
                        <validator />
                    </soapProxy>
    	</router>
    </spring:beans>

test.wsdl (Sample hello world wsdl with an import added)

    <definitions name="HelloService"
       targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl"
       xmlns="http://schemas.xmlsoap.org/wsdl/"
       xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
       xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl"
       xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
       <types>
           <schema xmlns="http://www.w3.org/2001/XMLSchema">
               <import namespace="http://www.capita-software-services.com/scp/base"/>
           </schema>
       </types>

       <message name="SayHelloRequest">
          <part name="firstName" type="xsd:string"/>
       </message>
	
       <message name="SayHelloResponse">
          <part name="greeting" type="xsd:string"/>
       </message>

       <portType name="Hello_PortType">
          <operation name="sayHello">
             <input message="tns:SayHelloRequest"/>
             <output message="tns:SayHelloResponse"/>
          </operation>
       </portType>

       <binding name="Hello_Binding" type="tns:Hello_PortType">
          <soap:binding style="rpc"
             transport="http://schemas.xmlsoap.org/soap/http"/>
          <operation name="sayHello">
             <soap:operation soapAction="sayHello"/>
             <input>
                <soap:body
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                   namespace="urn:examples:helloservice"
                   use="encoded"/>
             </input>
		
             <output>
                <soap:body
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                   namespace="urn:examples:helloservice"
                   use="encoded"/>
             </output>
          </operation>
       </binding>

       <service name="Hello_Service">
          <documentation>WSDL File for HelloService</documentation>
          <port binding="tns:Hello_Binding" name="Hello_Port">
             <soap:address
                location="http://www.examples.com/SayHello/" />
          </port>
       </service>
    </definitions>

`org.springframework.context.ApplicationContextException: Failed to start bean 'router'; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:170)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$1(DefaultLifecycleProcessor.java:154)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:339)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:143)
	at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:89)
	at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1259)
	at com.predic8.membrane.core.Router.init(Router.java:138)
	at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.predic8.membrane.core.Starter.main(Starter.java:26)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.predic8.membrane.core.Router.start(Router.java:270)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:167)
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.predic8.membrane.core.resolver.ResolverMap$1.resolveResource(ResolverMap.java:201)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1073)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:659)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.resolveSchema(XSDHandler.java:2052)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.constructTrees(XSDHandler.java:1008)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:620)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:616)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:574)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:540)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at com.predic8.membrane.core.interceptor.schemavalidation.AbstractXMLSchemaValidator.createValidators(AbstractXMLSchemaValidator.java:125)
	at com.predic8.membrane.core.interceptor.schemavalidation.AbstractXMLSchemaValidator.<init>(AbstractXMLSchemaValidator.java:68)
	at com.predic8.membrane.core.interceptor.schemavalidation.WSDLValidator.<init>(WSDLValidator.java:42)
	at com.predic8.membrane.core.interceptor.schemavalidation.ValidatorInterceptor.init(ValidatorInterceptor.java:96)
	at com.predic8.membrane.core.interceptor.AbstractInterceptor.init(AbstractInterceptor.java:103)
	at com.predic8.membrane.core.interceptor.schemavalidation.ValidatorInterceptor.init(ValidatorInterceptor.java:202)
	at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java:182)
	at com.predic8.membrane.core.Router.init(Router.java:241)
	at com.predic8.membrane.core.Router.start(Router.java:256)
	... 13 more
Caused by: java.lang.NullPointerException
	at com.predic8.membrane.core.resolver.ResolverMap$1.resolveResource(ResolverMap.java:197)
	... 33 more`

**Comment by predic8** [comment]
thx @longsonr for the detailed report
The exception is cause by the <validator /> tag. Seems that the Schema validator created by:

javax.xml.validation.SchemaFactory.newSchema

has a problem with the import.

**Comment by predic8** [comment]
In order to validate against WSDL you need to all the Schema definitions. So Membrane is right. It just generates an ugly exception. You nedd to add the schemaLocation to your import or you have to remove the validate interceptor.

**Comment by longsonr** [comment]
I completely understand and agree that membrane is right. I was, however hoping for the result of this issue to be a better error message.

**Comment by predic8** [comment]
You are right. We can improve the error message in a future version.
