### ISSUE TITLE
Starting Java 8 Membrane distributions with Java 7

### ISSUE THREAD

**Issue by xorpherion** [membrane/service-proxy#255]
What happens? Is there an error message?

**Comment by xorpherion** [comment]
When started with Java 7 the distribution gives the following ( or something similiar ) to this error: 
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/predic8/membrane/core/IDEStarter : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)`
After some research i come to the conclusion that it is not easily possible to catch this exception ( and then presenting a nice error message ) because the programm terminates before user code is ran.
