### ISSUE TITLE
Web socket: getting IndexOutOfBound exeception in com.predic8.membrane.core.transport.ws.WebSocketFrame#tryRead

### ISSUE THREAD

**Issue by zaguros** [membrane/service-proxy#299]
We are using 4.5.1 version as reverse proxy for web socket.
The proxy sometime unexpectedly close the socket connection.
When enabling debug logging we see this: 
```
2017-11-27 15:46:33,250 [RouterThread /0:0:0:0:0:0:0:1:55330 WebSocket Backward Thread] DEBUG	(WebSocketStreamPump.java) 
java.lang.ArrayIndexOutOfBoundsException: 8192
	at com.predic8.membrane.core.transport.ws.WebSocketFrame.tryRead(WebSocketFrame.java:233)
	at com.predic8.membrane.core.transport.ws.WebSocketFrameAssembler.readFrames(WebSocketFrameAssembler.java:52)
	at com.predic8.membrane.core.transport.http.WebSocketStreamPump.run(WebSocketStreamPump.java:70)
	at java.lang.Thread.run(Thread.java:745)
```

Thank you.

**Comment by github-ronk** [comment]
@rrayst - could you please have a look?  Thanks..

**Comment by xorpherion** [comment]
Hello,
i am currently working on this issue and will come back to it when i have some results.

**Comment by xorpherion** [comment]
I've commit a bugfix that respects the "header" part of a WebSocket frame. Could you try out the latest SNAPSHOT @zaguros ?

**Comment by zaguros** [comment]
Works for us :) @xorpherion

**Comment by zaguros** [comment]
When you create new branch with this fix?
