### ISSUE TITLE
NullPointerException while doing OAuth2 flow

### ISSUE THREAD

**Issue by DanielBo** [membrane/service-proxy#328]
```
15:11:08,495  WARN AbstractHttpHandler:89 - An exception occured while handling a request:
java.lang.NullPointerException
	at com.predic8.membrane.core.interceptor.oauth2.OAuth2ResourceInterceptor.refreshingOfAccessTokenIsNeeded(OAuth2ResourceInterceptor.java:316)
	at com.predic8.membrane.core.interceptor.oauth2.OAuth2ResourceInterceptor.handleRequestInternal(OAuth2ResourceInterceptor.java:248)
	at com.predic8.membrane.core.interceptor.oauth2.OAuth2ResourceInterceptor.handleRequest(OAuth2ResourceInterceptor.java:191)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
	at com.predic8.membrane.core.interceptor.UserFeatureInterceptor.handleRequest(UserFeatureInterceptor.java:43)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
	at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70)
	at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:234)
	at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xorpherion** [comment]
Which version is that?

https://github.com/membrane/service-proxy/blob/master/core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2ResourceInterceptor.java#L316

In the current version line 316 is completely different.

**Comment by rrayst** [comment]
This was either https://github.com/membrane/service-proxy/blob/4efed6878898e87c6c4c4fcd6808067189307f1c/core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2ResourceInterceptor.java or https://github.com/membrane/service-proxy/blob/081f15077e76d3a4e57d892e8421dab486679267/core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/OAuth2ResourceInterceptor.java .

The cause could be a problem on the OAuth2 Authorization Server.

We have not observed this for quite a while (and switched the clients to ``OAuth2Resource2Interceptor`` since).
