### ISSUE TITLE
SwaggerProxy does not resolve some URLs

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#336]
<swaggerProxy port="7000" url="https://api.predic8.de/shop/swagger" />

works fine. But:

<swaggerProxy port="7000" url="https://raw.githubusercontent.com/bpmason1/panthip-swagger/master/swagger.json" />

throws a FileNotFound Exception

See the Mail Report from Brian below:

 I'm trying to proxy a toy swagger file using membrane but I keep getting the error pasted below.  I was wondering if you had any idea what I'm doing wrong.  The url to the swagger.json file is definitely valid.  My proxies.xml file is attached  Also, an unrelated question, does membrane support yaml formatted swagger files or does it only support json?

The error:
Membrane Router running...
20:25:39,211  INFO TrackingFileSystemXmlApplicationContext:583 - Refreshing Membrane Service Proxy's Spring Context
20:25:39,291  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from URL [file:/home/bmason/Projects/membrane/membrane-service-proxy-4.6.2/conf/proxies.xml]
20:25:40,263  INFO DefaultLifecycleProcessor:345 - Starting beans in phase 0
org.springframework.context.ApplicationContextException: Failed to start bean 'router'; nested exception is java.lang.RuntimeException: com.predic8.membrane.core.resolver.ResourceRetrievalException: java.io.FileNotFoundException: swagger.json (No such file or directory) while retrieving swagger.json
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:350)
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:92)
at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1305)
at com.predic8.membrane.core.Router.init(Router.java:146)
at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.predic8.membrane.core.Starter.main(Starter.java:26)
Caused by: java.lang.RuntimeException: com.predic8.membrane.core.resolver.ResourceRetrievalException: java.io.FileNotFoundException: swagger.json (No such file or directory) while retrieving swagger.json
at com.predic8.membrane.core.Router.start(Router.java:285)
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
... 12 more
Caused by: com.predic8.membrane.core.resolver.ResourceRetrievalException: java.io.FileNotFoundException: swagger.json (No such file or directory) while retrieving swagger.json
at com.predic8.membrane.core.resolver.FileSchemaResolver.resolve(FileSchemaResolver.java:75)
at com.predic8.membrane.core.resolver.ResolverMap.resolve(ResolverMap.java:181)
at com.predic8.membrane.core.interceptor.swagger.SwaggerRewriterInterceptor.init(SwaggerRewriterInterceptor.java:80)
at com.predic8.membrane.core.interceptor.AbstractInterceptor.init(AbstractInterceptor.java:105)
at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java:171)
at com.predic8.membrane.core.Router.init(Router.java:256)
at com.predic8.membrane.core.Router.start(Router.java:270)
... 13 more
Caused by: java.io.FileNotFoundException: swagger.json (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at com.predic8.membrane.core.resolver.FileSchemaResolver.resolve(FileSchemaResolver.java:73)
... 19 more

**Comment by rrayst** [comment]
it looks like Membrane tries to open a file (``FileInputStream`` via ``FileSchemaResolver``), not a URL (via the ``HttpSchemaResolver``). can you paste the proxies.xml?

**Comment by bpmason1** [comment]
```
<!--

	Main configuration

	See https://www.membrane-soa.org/service-proxy-doc/4.4/configuration/samples.htm
	or proxies-full-sample.xml.

	In the examples/* folders are working samples for proxies.xml

-->
<spring:beans xmlns="http://membrane-soa.org/proxies/1/"
			  xmlns:spring="http://www.springframework.org/schema/beans"
			  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:schemaLocation="http://www.springframework.org/schema/beans
	                    http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
	                    http://membrane-soa.org/proxies/1/ http://membrane-soa.org/schemas/proxies-1.xsd">

	<router>
        <swaggerProxy port="7000" url="https://raw.githubusercontent.com/bpmason1/panthip-swagger/master/swagger.json" />
	</router>

</spring:beans>
```

**Comment by rrayst** [comment]
The swagger library currently contained in Membrane Service Proxy does not yet support OpenAPI. It expects a 'swagger' key on the top level of the JSON object.

**Comment by bpmason1** [comment]
How hard is it to update the library?

**Comment by bridgerdier** [comment]
OpenAPI should be handled correctly now, please test. We'd also be interested to hear about possible regressions introduced by this change.

**Comment by symle** [comment]
I try it too, It works as expected. Could you please test one more time?

**Comment by rrayst** [comment]
please reopen, if required
