### ISSUE TITLE
Exception with FileExchangeStore after upgrading to Membrane v4.7.1

### ISSUE THREAD

**Issue by jRom42** [membrane/service-proxy#351]
Hi,

We recently upgraded Membrane Service Proxy to version 4.7.1 and started having issues with web services which were working fine before.
The only workaround we found to make it work again is to disable file exchange store in those services.
We get the following error when service is called with file echange store enabled:

```
[2020-08-03 13:56:12,279] DEBUG HttpClient:186 - try # 0 to http://report-test.xxxx.xxx:80/rest/
[2020-08-03 13:56:12,279] DEBUG ConnectionManager:145 - connection requested for report-test.xxxx.xx:80
[2020-08-03 13:56:12,279] DEBUG ConnectionManager:147 - Number of connections in pool: 2
[2020-08-03 13:56:12,280] DEBUG Connection:111 - Opened connection on localPort: 46356
[2020-08-03 13:56:12,280] DEBUG ChunkedBody:123 - writeNotReadChunked
[2020-08-03 13:56:42,314] ERROR FileExchangeStore:124 - java.net.SocketTimeoutException: Read timed out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at com.predic8.membrane.core.util.HttpUtil.readChunkSize(HttpUtil.java:87)
        at com.predic8.membrane.core.http.ChunkedBody$1.readNextChunk(ChunkedBody.java:99)
        at com.predic8.membrane.core.http.BodyInputStream.advanceToNextPosition(BodyInputStream.java:72)
        at com.predic8.membrane.core.http.BodyInputStream.read(BodyInputStream.java:111)
        at java.io.InputStream.read(InputStream.java:101)
        at com.predic8.membrane.core.util.ByteUtil.readStream(ByteUtil.java:71)
        at com.predic8.membrane.core.http.ChunkedBody.read(ChunkedBody.java:47)
        at com.predic8.membrane.core.http.AbstractBody.getContent(AbstractBody.java:100)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore.writeFile(FileExchangeStore.java:177)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore.snapInternal(FileExchangeStore.java:116)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore.access$000(FileExchangeStore.java:52)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore$1.bodyComplete(FileExchangeStore.java:88)
        at com.predic8.membrane.core.http.AbstractBody.markAsRead(AbstractBody.java:74)
        at com.predic8.membrane.core.http.ChunkedBody.markAsRead(ChunkedBody.java:60)
        at com.predic8.membrane.core.http.ChunkedBody.writeNotRead(ChunkedBody.java:135)
        at com.predic8.membrane.core.http.AbstractBody.write(AbstractBody.java:124)
        at com.predic8.membrane.core.http.ChunkedBody.write(ChunkedBody.java:55)
        at com.predic8.membrane.core.http.Message.write(Message.java:233)
        at com.predic8.membrane.core.transport.http.HttpClient.doCall(HttpClient.java:360)
        at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:216)
        at com.predic8.membrane.core.interceptor.HTTPClientInterceptor.handleRequest(HTTPClientInterceptor.java:60)
        at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
        at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
        at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:234)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-08-03 13:56:42,318] DEBUG Response:376 - empty body created
[2020-08-03 13:56:42,318] DEBUG InterceptorFlowController:126 - Invoking response handler: WSDL Rewriting Interceptor on exchange: [time:Aug 3, 2020,requestURI:/rest/]
[2020-08-03 13:56:42,318] DEBUG RelocatingInterceptor:45 - WSDL Rewriting Interceptor HTTP method wasn't GET: No relocating done!
``` 

Request headers

```
Content-Type	application/json
Accept	*/*
User-Agent	Apache-CXF/3.2.6
Cache-Control	no-cache
Pragma	no-cache
Host	report-test.xxxx.xxx:80
Connection	keep-alive
Transfer-Encoding	chunked
X-Forwarded-For	xxx.xxx.xxx.xxx
X-Forwarded-Proto	http
X-Forwarded-Host	somehost.xxx.xx
```

Request content

```
{
    "bucketName": "expat",
    "objectName": "xxx.xxx-xx__E68_ex_lettre_etr_autre_20200803134639_1596462399846.pdf",
    "reportTemplateName": "EX_LETTRE_ETR_AUTRE",
    "reportLocale": "FR",
    "reportType": "pdf",
    "reportParameters": {
        "P_LOGO": "CIAM"
    },
    "data": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Document>....<\/Document>"
}
```

**Comment by predic8** [comment]
Hi,
can you post also the proxies.xml file? I can see in the trace the WSDL Rewriter but the content is JSON. Do you request a WSDL containing imports?

**Comment by jRom42** [comment]
Hi,

Thanks for taking time to answer.
You are right wsdlRewiter should not be present. 
Here is our working proxies.xml configuration (fileexchangestore is commented):

```
<!-- Routing Configuration Here you can configure routing rules for Membrane Service Proxy. It contains some rules to show how to setup routing. Please make sure to remove these rules before you put the router into production. More sample configurations you can find in the examples directory. Have a look at http://membrane-soa.org/service-proxy-doc/current/configuration/proxy-configuration.htm for documentation and a reference explaining what XML elements can be used how and where. See the proxies.xml files in the /examples/* directories in the Service Proxy distribution for several examples of how to configure different Service Proxy features within this file. Changes to this file will be picked up almost instantly if Membrane is running once this file has been saved. Any dynamic configuration changes made (for example, via the adminConsole) will be forgotten. -->
<spring:beans xmlns="http://membrane-soa.org/proxies/1/" xmlns:spring="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd http://membrane-soa.org/proxies/1/ http://membrane-soa.org/schemas/proxies-1.xsd">

  <router exchangeStore="limitedMemoryExchangeStore">
    <!-- Sets up the Administration Web Interface on port 9000-->
    <serviceProxy name="Console" port="9000">
      <basicAuthentication>
        <user name="xxxxxxxxx" password="xxxxxxxxx" />
      </basicAuthentication>
      <adminConsole />
    </serviceProxy>
    
    <!--
    ###########################################################################
    Proxy pour MinIO Rest API
    ###########################################################################
    -->
    <serviceProxy name="minioRestServices" host="xxxxxxx.xxx.xx">
        <path>/minioRestServices</path>
        <!-- <exchangeStore name="fes" /> -->
        <rewriter>
            <map from="^/minioRestServices" to="" />
        </rewriter>
        <wsdlRewriter port="80" protocol="http" host="xxxxxxx.xxx.xx" />
        <target host="minio-rest-prod.fsp.ch" port="80" />
    </serviceProxy>
    
	</router>
  <fileExchangeStore dir="/data/xxxxxx/xxxxxxxxx/logs" raw="false" saveBodyOnly="false" id="fes"/>
  <limitedMemoryExchangeStore maxSize="128000000"/>
</spring:beans>

```

**Comment by predic8** [comment]
When does the exception happen. Always or only when you request the WSDL document?

**Comment by jRom42** [comment]
Everytime.
We do not make a call to the wsdl it's a REST service.
The wsdlrewriter is a mistake from a copy/paste.

**Comment by predic8** [comment]
In the proxies.xml above the wsdlRewriter is present. But you are sure that the it is not present yet. Then try it again and please post the stacktrace here.

**Comment by jRom42** [comment]
Removed the wsdlrewriter and activated fileexchangestore then I get same exception stacktrace (see below).
If I also remove the fileexchangestore directive then no more exception.



```
[2020-08-11 09:14:45,192]  INFO Router:291 - Membrane Service Proxy 4.7.1 up and running!
[2020-08-11 09:15:29,588] ERROR FileExchangeStore:124 - java.net.SocketException: Socket closed
java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at com.predic8.membrane.core.util.HttpUtil.readChunkSize(HttpUtil.java:87)
        at com.predic8.membrane.core.http.ChunkedBody$1.readNextChunk(ChunkedBody.java:99)
        at com.predic8.membrane.core.http.BodyInputStream.advanceToNextPosition(BodyInputStream.java:72)
        at com.predic8.membrane.core.http.BodyInputStream.read(BodyInputStream.java:111)
        at java.io.InputStream.read(InputStream.java:101)
        at com.predic8.membrane.core.util.ByteUtil.readStream(ByteUtil.java:71)
        at com.predic8.membrane.core.http.ChunkedBody.read(ChunkedBody.java:47)
        at com.predic8.membrane.core.http.AbstractBody.getContent(AbstractBody.java:100)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore.writeFile(FileExchangeStore.java:177)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore.snapInternal(FileExchangeStore.java:121)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore.access$000(FileExchangeStore.java:52)
        at com.predic8.membrane.core.exchangestore.FileExchangeStore$1.bodyComplete(FileExchangeStore.java:88)
        at com.predic8.membrane.core.http.AbstractBody.markAsRead(AbstractBody.java:74)
        at com.predic8.membrane.core.http.ChunkedBody.markAsRead(ChunkedBody.java:60)
        at com.predic8.membrane.core.http.ChunkedBody.writeNotRead(ChunkedBody.java:135)
        at com.predic8.membrane.core.http.AbstractBody.write(AbstractBody.java:124)
        at com.predic8.membrane.core.http.ChunkedBody.write(ChunkedBody.java:55)
        at com.predic8.membrane.core.http.Message.write(Message.java:233)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.writeResponse(HttpServerHandler.java:292)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:250)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-08-11 09:15:29,600] ERROR HttpServerHandler:162 -
java.lang.RuntimeException: java.io.IOException: Stream closed
        at com.predic8.membrane.core.http.Message.estimateHeapSize(Message.java:368)
        at com.predic8.membrane.core.http.Response.estimateHeapSize(Response.java:440)
        at com.predic8.membrane.core.exchange.AbstractExchange.estimateHeapSize(AbstractExchange.java:427)
        at com.predic8.membrane.core.exchange.AbstractExchange.getHeapSizeEstimation(AbstractExchange.java:413)
        at com.predic8.membrane.core.exchangestore.LimitedMemoryExchangeStore.snapInternal(LimitedMemoryExchangeStore.java:183)
        at com.predic8.membrane.core.exchangestore.LimitedMemoryExchangeStore.access$200(LimitedMemoryExchangeStore.java:38)
        at com.predic8.membrane.core.exchangestore.LimitedMemoryExchangeStore$5.bodyComplete(LimitedMemoryExchangeStore.java:166)
        at com.predic8.membrane.core.http.AbstractBody.markAsRead(AbstractBody.java:74)
        at com.predic8.membrane.core.http.ChunkedBody.markAsRead(ChunkedBody.java:60)
        at com.predic8.membrane.core.http.ChunkedBody.writeNotRead(ChunkedBody.java:135)
        at com.predic8.membrane.core.http.AbstractBody.write(AbstractBody.java:124)
        at com.predic8.membrane.core.http.ChunkedBody.write(ChunkedBody.java:55)
        at com.predic8.membrane.core.http.Message.write(Message.java:233)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.writeResponse(HttpServerHandler.java:292)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:250)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:214)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at com.predic8.membrane.core.util.HttpUtil.readChunkSize(HttpUtil.java:87)
        at com.predic8.membrane.core.http.ChunkedBody$1.readNextChunk(ChunkedBody.java:99)
        at com.predic8.membrane.core.http.BodyInputStream.advanceToNextPosition(BodyInputStream.java:72)
        at com.predic8.membrane.core.http.BodyInputStream.read(BodyInputStream.java:111)
        at java.io.InputStream.read(InputStream.java:101)
        at com.predic8.membrane.core.util.ByteUtil.readStream(ByteUtil.java:71)
        at com.predic8.membrane.core.http.ChunkedBody.read(ChunkedBody.java:47)
        at com.predic8.membrane.core.http.AbstractBody.getLength(AbstractBody.java:151)
        at com.predic8.membrane.core.http.Message.estimateHeapSize(Message.java:365)
        ... 18 more

```

**Comment by predic8** [comment]
Use only one ExchangeStore. The stores reads a stream for performance reasons. After reading the stream is empty. Reading it a second time will result in the error.
