### ISSUE TITLE
How do I connect to a Private IP running https?

### ISSUE THREAD

**Issue by phunghop** [membrane/service-proxy#355]
I have problem with
Private URL: **https**://192.168.69.64
How to configure the connection to?

I configure the following, but it doesn't work
```
<serviceProxy name="Proxy" port="2022">
	<ssl>
		<keystore location="***" password="***" keyPassword="***" />
		<truststore location="***" password="***" />
	</ssl>
	<target host="192.68.69.64">
		<ssl />
	</target>		
</serviceProxy>

```
Please help me!
Thanks!

**Comment by rrayst** [comment]
Please checkout the ssl-client example.

**Comment by phunghop** [comment]
Thanks for your support
I have the configuration according to the example
```
<serviceProxy name="Proxy" port="2022">
	<ssl>
		<keystore location="***" password="***" keyPassword="***" />
		<truststore location="***" password="***" />
	</ssl>
	<target host="192.168.69.64" port="443">
		<ssl ignoreTimestampCheckFailure="true" />
	</target>
</serviceProxy>
```
Then there is an error
```
20:33:00,716 ERROR HttpServerHandler:146 -
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:765)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.predic8.membrane.core.http.Message.write(Message.java:235)
        at com.predic8.membrane.core.transport.http.HttpClient.doCall(HttpClient.java:360)
        at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:216)
        at com.predic8.membrane.core.interceptor.HTTPClientInterceptor.handleRequest(HTTPClientInterceptor.java:60)
        at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
        at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
        at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:234)
        at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
        at sun.security.validator.Validator.validate(Validator.java:262)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)
        at com.predic8.membrane.core.transport.TrustManagerWrapper.checkServerTrusted(TrustManagerWrapper.java:95)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1099)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
        ... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
        ... 29 more
```

**Comment by predic8** [comment]
You have to setup your keystores properly and make sure that the signing path can be followed up to a root certificate.

**Comment by phunghop** [comment]
Private URL (**https://192.168.69.64**) always runs on https but doesn't have SSL security so I don't have a keystore to configure.
So what should I do in this case?

Please help me!
Thanks!

**Comment by rrayst** [comment]
```
<serviceProxy name="Proxy" port="2022">
	<ssl>
		<!-- ... does not matter, as this configures *inbound* SSL -->
	</ssl>
	<target host="192.168.69.64" port="443">
		<ssl ignoreTimestampCheckFailure="true"> <!-- this configures outbound SSL, which is what you want IIRC -->
                          <truststore location="***" password="***" />
                </ssl>
	</target>
</serviceProxy>
```

In the truststore, some certificate has to be present authenticating your remote server https://192.168.69.64 .
