### ISSUE TITLE
Qualified Error Messages instead of some StackTraces

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#466]
For the 5 most common Exceptions in the Log.

Put the Stacetraces inside this ticket

**Comment by predic8** [comment]
The following exception:

java.lang.NumberFormatException: For input string: "//spain.predic8.de"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:651) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
	at com.predic8.membrane.core.transport.http.HostColonPort.<init>(HostColonPort.java:32) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.transport.http.HttpClient.getTargetHostAndPort(HttpClient.java:169) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.transport.http.HttpClient.init(HttpClient.java:176) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:227) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.interceptor.HTTPClientInterceptor.handleRequest(HTTPClientInterceptor.java:67) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:108) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:73) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:220) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:124) ~[service-proxy-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]

Will return:

{"error":"This request was not accepted by Membrane. Please check HTTP method and path."}%

and log nothing with the master at this time.

**Comment by predic8** [comment]
Exceptions only show up with debugSSL config set.
