### ISSUE TITLE
SSL OpenJDK Error in Membrane Dockerimage 5.1

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#710]
During SSL Handshake you get:

javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
        at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source) ~[?:?]
        at java.io.BufferedInputStream.fill(Unknown Source) ~[?:?]
        at java.io.BufferedInputStream.implRead(Unknown Source) ~[?:?]
        at java.io.BufferedInputStream.read(Unknown Source) ~[?:?]
        at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:98) ~[service-proxy-core-5.1.19.jar:5.1.19]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
        at sun.security.ssl.SSLCipher$T13CC20P1305ReadCipherGenerator$CC20P1305ReadCipher.decrypt(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source) ~[?:?]
        ... 13 more

This is a know issue in OpenJDK

See: https://bugs.openjdk.org/browse/JDK-8221218

We should update the Docker Image in Membrane 5.2.

**Comment by koin612** [comment]
I think we should also check for #562 in this case.

**Comment by predic8** [comment]
I could not reproduce it locally. Maybe it only happens with some server. We will change the base image of the dockerfile to a stable Java 17 and see.
